name: Issue closer

on:
  issues:
    types: [opened, edited, reopened]

jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
      - name: Autoclose issues
        uses: arkon/issue-closer-action@v3.0
        with:
          repo-token: ${{ github.token }}
          rules: |
            [
              {
                "type": "title",
                "regex": ".*<short description>*",
                "message": "You did not fill out the description in the title"
              },
              {
                "type": "body",
                "regex": ".*DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT.*",
                "message": "The acknowledgment section was not removed"
              },
              {
                "type": "body",
                "regex": "(Tachidesk version|Server Operating System|Server JVM version|Client Operating System|Client Web Browser):.*(\\(Example:|<usually).*",
                "message": "The requested information was not filled out"
              }
            ]
